### ISSUE TITLE
Cannot connect to mesh

### ISSUE THREAD

**Issue by zimmra** [yangqian/hass-gelight#1]
Home Assistant Info:
Version | 0.118.3
-- | --
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
Virtual Environment | false
Python Version | 3.8.6
Operating System Family | Linux
Operating System Version | 5.4.0-53-generic
CPU Architecture | x86_64

I have bluepy and dimond installed within the container

I can see my devices when using bluetoothctl scan within the container

I have the gelight directory in the custom_components directory

Example of my config (values privatized):
```
light:
  - platform: gelight
    password: 114782
    username: 09468793751B
    lights:
      - id: 1
        mac: f4:bc:da:3b:3b:2c
        name: Vanity 2
        type: 21
      - id: 2
        mac: f4:bc:da:3c:5b:0f
        name: Vanity 5
        type: 21
      - id: 3
        mac: f4:bc:da:3b:c1:2p
        name: Vanity 1
        type: 21
      - id: 4
        mac: f4:bc:da:3b:00:97
        name: Vanity 3
        type: 6
      - id: 5
        mac: f4:bc:da:3a:ee:7d
        name: Vanity 4
        type: 6
      - id: 6
        mac: f4:bc:da:3b:87:4a
        name: Vanity 6
        type: 21
```

Error thrown:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/gelight/light.py", line 107, in async_setup_platform
    await hass.async_add_executor_job(mesh.connect)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gelight/light.py", line 303, in connect
    raise Exception("Unable to connect to mesh %s" % self.address)
Exception: Unable to connect to mesh 09468793751B
```

**Comment by zimmra** [comment]
I suspect this has something to do with docker, as I got it working in a separate instance outside of docker on a different machine.

**Comment by yangqian** [comment]
I am glad you can connect to the bulbs now.
I am running the home assistant without docker. I am not sure if or how should the bluetooth work inside the docker container.

**Comment by austin-engle** [comment]
I am seeing this same error in both docker and hass.io running on pi3b+
