### ISSUE TITLE
directions to install bluepy and diamond?

### ISSUE THREAD

**Issue by austin-engle** [yangqian/hass-gelight#4]
I am trying to follow this guide but I am unable to figure out how to install bluepy and diamond. I am running Hassio on a pi3b+. It appears python isn't available to the system but I'm not 100% sure.

**Comment by yangqian** [comment]
Hi,

I installed home assistant to coreelec directly via pip install on a Amlogic device.
bluepy and dimond are both available via pip or GitHub.

I do not own Hassio nor pi3b+. So I cannot comment much on this.

**Comment by Dperrigo18** [comment]
Is it possible to link to the pip package you installed or setup a simple guide on how to setup this up with your Home Assistant.
I wouldn't mind setting my Home Assistant up again if I could connect these light bulbs to them but I have no success using Hassio and this add-on, it comes up with errors about installing bluepy and diamond.

**Comment by yangqian** [comment]
> 

Have you tried to install via HACS? It may install the dependency of bluepy and dimond for you. Alternatively, though could be installed by
```
pip3 install bluepy
pip3 install dimond
```

**Comment by Dperrigo18** [comment]
So this is what I have so far.
I'm using the Home Assistant Operating System.
I have HACS installed with GE Light Local Bluetooth Controller Installed as a Integration.
I have the output of the script in my config file.
When validating it I get: Platform error light.gelight - Integration 'gelight' not found.
I think I misunderstood and my main issue is running the Home Assistant Operating System which I think is why I can't install the packages manually since its stripped down and its having its own internal issues installing then itself.
What way do run Home Assistant? I did it this way since it was the easiest at the time.

**Comment by zimmra** [comment]
You can do it with Home Assistant OS

If you are having trouble with bluepy and diamond use the 'Custom deps deployment' addon (Configuration > Add-Ons, Backups, & Supervisor, then Addon-Store, then install Custom deps deployment)

The following config within Custom deps deployment worked for me

```
pypi:
  - git+https://github.com/mjg59/bluepy@local_version#egg=bluepy_mjg59
  - git+https://github.com/mjg59/bluepy@local_version#egg=bluepy
  - dimond
apk:
  - glib
  - glib-dev
  - build-base
```

**Comment by GHanthorn** [comment]
I am having the same issue and can't find Custom deps deployment

**Comment by Dperrigo18** [comment]
So I found you have to add the Home Assistant Developer repository so it will show up under addons.
https://github.com/home-assistant/addons-development
I added it and the config the zimmra provided works to install all the dependencies. You do need to restart after it runs.
My next issue is after restarting I don't get any more errors about dependencies but I do get this.
I made sure and checked that I pasted the output of the script correctly.
```
Logger: homeassistant.components.light
Source: custom_components/gelight/light.py:318
Integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 9:24:27 PM (1 occurrences)
Last logged: 9:24:27 PM
Error while setting up gelight platform for light

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/gelight/light.py", line 109, in async_setup_platform
    await hass.async_add_executor_job(mesh.connect)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gelight/light.py", line 318, in connect
    raise Exception("Unable to connect to mesh %s" % self.address)
Exception: Unable to connect to mesh 5E69CD18E938192C
```

**Comment by zimmra** [comment]
> ```
> 
> Exception: Unable to connect to mesh 5E69CD18E938192C
> 
> ```

That string looks way too long. Are you sure that's what the config generator output? 

Could you post your config?

**Comment by Dperrigo18** [comment]
I ran the script and this is the output.
```
[temp]$ python3 ./getconfig.py 
Refresh token (if available): 
`user_id` (if available): 
Enable debug output? (y/N): 
Cync Username/Email: temp
Password: 
Enter emailed code: 111111
light:
  - platform: gelight
    password: 957309
    username: 5E69CD18E938192C
    lights:
      - id: 1
        mac: a4::c:1::38::5:5:
        name: Family Room Lamp
        type: 18
```
If you want me to send you the debug data let me know.

**Comment by yangqian** [comment]
> 

Could you try the old get config script at 
https://raw.githubusercontent.com/yangqian/hass-gelight/673e56900d293a3964955b88fb0cfbae9e0f3952/getconfig.py
The script was updated but I don't have the device any more so it could not be tested.

**Comment by Dperrigo18** [comment]
So I ran it and the output looks slightly different.
Also thanks for the help!
```
[temp]$ python3 getconfig.py 
Cync Username/Email:temp
Password: 
Enter emailed code:111111
light:
  - platform: gelight
    password: 957309
    username: 5E69CD18E938192C
    lights:
      - id: 1
        mac: 5:::5:38:1:::C:A4
        name: Family Room Lamp
        type: 18
```
