### ISSUE TITLE
Unable to use lightbulb in automations

### ISSUE THREAD

**Issue by pcon** [yangqian/hass-gelight#5]
I cannot use the bulb in any automations because it "does not have a unique ID."  Is there a way to specify the entity_id in the configuration file so that automations can be run against the device?  The error text points to [this](https://www.home-assistant.io/faq/unique_id) documentation.

**Comment by yangqian** [comment]
It does not have a unique ID. However, you could still use it in automations.
It just means that it cannot be configured in this UI panel.
You can still edit in the automation or script UI panel (or a yaml file).
The entity_id should be light.name_of_your_light.
